### ISSUE TITLE
JSON with comments compatability

### ISSUE THREAD

**Issue by glen-nicol** [richie5um/vscode-statusbar-json-path#11]
I use the JSON with comments language in VS code a lot when working with example files that are illustrating the use of a schema. It would be great if this plugin could support that as well.

**Comment by richie5um** [comment]
I can easily add support for that file type, but as this extension will probably fail due to the comments, it may not be entirely successful.

I'll do the change later today.

**Comment by richie5um** [comment]
I've added this and published as v1.2.0.

Note: It may have issues depending on the contents of the comments.
