### ISSUE TITLE
Add support for Amazon State Language and AWS Systems Manager Document (JSON)

### ISSUE THREAD

**Issue by amehta-rms** [richie5um/vscode-statusbar-json-path#24]
Love this extension as it is very useful but it currently only works for `json` and `jsonc` languages.

Would it be possible to extend the list of supported languages to include:

1. Amazon State Language (`asl`): They typically have `asl.json` file extension but they are essentially JSON .
2. AWS Systems Manager Document (JSON) (`ssm-json`)

Thanks.

**Comment by richie5um** [comment]
Done. Will be in version 1.4.5
