### ISSUE TITLE
which version is compatible with vs code 1.39.2?

### ISSUE THREAD

**Issue by hairinwind** [richie5um/vscode-statusbar-json-path#25]
My company only allows vs code 1.39.2 to be used. 
I tried all the versions here https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-statusbar-json-path&ssr=false#version-history
but none of them is compatible with vs code 1.39.2. 

Can I get an older version?

**Comment by richie5um** [comment]
Hi, I know this isn't particularly helpful, but I'd suggest you'd be best to pull this repo to your machine and install the extension locally - and fix it up until it works.
