### ISSUE TITLE
Hide "Invalid JSON" when active file is not a JSON.

### ISSUE THREAD

**Issue by aarongarciah** [richie5um/vscode-statusbar-json-path#4]
Hi @richie5um. Very nice extension, congratulations.

I wonder if it's possible to hide in the status bar the message "Invalid JSON" when the active file is not a JSON. This occurs once the user has opened a JSON file and switches to another file that is not a JSON.

![jsonpath](https://cloud.githubusercontent.com/assets/7225802/24196769/5131d042-0eff-11e7-9077-caeb6278ebbb.jpg)

**Comment by richie5um** [comment]
Thanks for creating an issue. Fixed :).

**Comment by aarongarciah** [comment]
Thank you for fixing the issue 😄

**Comment by robertmassaioli** [comment]
I'm still getting this issue. JSONPath is showing up on every file in Visual Studio Code for me.

**Comment by robertmassaioli** [comment]
This is what I see @richie5um : 

<img width="1199" alt="screen shot 2018-11-18 at 12 43 04 pm" src="https://user-images.githubusercontent.com/149178/48667669-b48e1200-eb2f-11e8-8c15-00771c4e2de3.png">

As you can see, the problem persists. The version is `1.2.0`.
