### ISSUE TITLE
copy to clipboard is not working on Linux

### ISSUE THREAD

**Issue by nicosampler** [richie5um/vscode-statusbar-json-path#5]
the copy to the clipboard is not working in my Debian.

**Comment by richie5um** [comment]
Is there anything in the output log? Is there an error?

**Comment by nicosampler** [comment]
no, it just does not overwrite the clipboard with the key.

**Comment by richie5um** [comment]
Ok, thanks. I'll try and set up a Debian VM to see if I can identify the issue.

**Comment by richie5um** [comment]
Set-up the VM and have reproduced the issue. I'll investigate and get back to you. Thanks.

**Comment by richie5um** [comment]
Found the problem, and have a solution :).

The issue is that the copy/paste package that is used relies on 'xclip' tool on Linux. But, xclip isn't installed by default on Debian. Run 'apt-get install xclip' and it'll start working.

**Comment by nicosampler** [comment]
now is working. Thanks so much!
