### ISSUE TITLE
Issue with Visual Studio Code version 1.20.1

### ISSUE THREAD

**Issue by dkriefgsx** [richie5um/vscode-statusbar-json-path#8]
Each time I want to get the JSON Path from a JSON file, there is a tooltip containing the message: "Loading...". 
Plus, my CPU is overloading to 90%.

If you can fix this, it will be really appreciated because your Extension is great !

**Comment by richie5um** [comment]
90% cpu!! That isn’t good :-(. 

Can you send me the JSON that is causing this to happen? I can’t seem to cause that behaviour on my machine.

**Comment by dkriefgsx** [comment]
Hi,

Thanks for your quick reply ! You will find the json having an issue below:

As an example, try to get the path for line 498.

{
  "EntityScanResult":
  {
    "ServiceScanResults": [
      {
        "ScanComponentResults": [
          {
            "$testType": "Test",
            "Information": {
              "State": "Unknown",
              "Message": "",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "1997-01-01T00:00:00",
              "Boolean": false
            },
            "Index": 0.0
          },
          {
            "$testType": "Test",
            "Results": [],
            "Information": {
              "State": "Up",
              "Message": "No windows services configured",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "Index": 1.0
          },
          {
            "$testType": "Test",
            "Information": {
              "State": "Up",
              "Message": "",
              "Tooltip": "",
              "TimeSpan": "00:00:07.1600000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "Results": {
              "0": {
                "Success": true,
                "Date": "2016-11-10T14:08:03.1241695+01:00",
                "ErrorMessage": "",
                "Time": "00:00:01.1190000",
                "Values": {
                  "$testTypes": [
                    "Double",
                    "String",
                    "String"
                  ],
                  "$values": [
                    [
                      6.3177978097251,
                      "_total",
                      "\\\\let\\"
                    ]
                  ]
                }
              },
              "1": {
                "Success": true,
                "Date": "2016-11-10T14:08:04.2494569+01:00",
                "ErrorMessage": "",
                "Time": "00:00:01.1890000",
                "Values": {
                  "$testTypes": [
                    "Double",
                    "String",
                    "String"
                  ],
                  "$values": [
                    [
                      4315.0,
                     "",
                      "\\\\let\\"
                    ]
                  ]
                }
              },
              "2": {
                "Success": true,
                "Date": "2016-11-10T14:08:05.4406431+01:00",
                "ErrorMessage": "",
                "Time": "00:00:01.0240000",
                "Values": {
                  "$testTypes": [
                    "Double",
                    "String",
                    "String"
                  ],
                  "$values": [
                    [
                      455.230984201384,
                      "",
                      "\\\\let\\"
                    ]
                  ]
                }
              },
              "3": {
                "Success": true,
                "Date": "2016-11-10T14:08:06.4512635+01:00",
                "ErrorMessage": "",
                "Time": "00:00:01.0230000",
                "Values": {
                  "$testTypes": [
                    "Double",
                    "String",
                    "String"
                  ],
                  "$values": [
                    [
                      0.0,
                      "_total",
                      "\\\\let\\"
                    ]
                  ]
                }
              },
              "4": {
                "Success": true,
                "Date": "2016-11-10T14:08:07.4759336+01:00",
                "ErrorMessage": "",
                "Time": "00:00:01.0240000",
                "Values": {
                  "$testTypes": [
                    "Double",
                    "String",
                    "String"
                  ],
                  "$values": [
                    [
                      0.0578170969348993,
                      "0 c:",
                      "\\\\let\\"
                    ],
                    [
                      0.0578170969348993,
                      "_total",
                      "\\\\let\\"
                    ]
                  ]
                }
              }
            },
            "Index": 2.0
          },
          {
            "$testType": "Test",
            "Results": [
              {
                "Name": "S2",
                "IsUp": true
              },
              {
                "Name": "S3",
                "IsUp": true
              }
            ],
            "Information": {
              "State": "Up",
              "Message": "Step4",
              "Tooltip": "",
              "TimeSpan": "00:00:03.1690000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "Index": 3.0
          },
          {
            "$testType": "Test",
            "Information": {
              "State": "Warning",
              "Message": "Threshold:\n\t\\\\?\\Volume{c74cfac6-76fc-49d4-9acd-13e45799a56a}\\: Free space = 135.06 MB",
              "Tooltip": "",
              "TimeSpan": "00:00:02.1120000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "AllKnownDisks": [
              "C:",
              "\\\\?\\Volume{c74cfac6-76fc-49d4-9acd-13e45799a56a}\\"
            ],
            "Results": [
              {
                "Name": "C:",
                "TotalSize": 83305468.0,
                "FreeSpace": 52643808.0
              },
              {
                "Name": "\\\\?\\Volume{c74cfac6-76fc-49d4-9acd-13e45799a56a}\\",
                "TotalSize": 460796.0,
                "FreeSpace": 138300.0
              }
            ],
            "Index": 4.0
          },
          {
            "$testType": "Test",
            "Information": {
              "State": "Up",
              "Message": "",
              "Tooltip": "",
              "TimeSpan": "00:00:00.0390000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "Results": {
              "0": {
                "Success": true,
                "Date": "2016-11-10T14:08:01.3268709+01:00",
                "ErrorMessage": "",
                "Time": "00:00:00.0130000",
                "Values": {}
              },
              "1": {
                "Success": true,
                "Date": "2016-11-10T14:08:01.3268709+01:00",
                "ErrorMessage": "",
                "Time": "00:00:00.0050000",
                "Values": {}
              },
              "2": {
                "Success": true,
                "Date": "2016-11-10T14:08:01.3430106+01:00",
                "ErrorMessage": "",
                "Time": "00:00:00.0010000",
                "Values": {
                  "$testTypes": [
                    "String",
                    "Double",
                    "String"
                  ],
                  "$values": [
                    [
                      "True",
                      1.0,
                      ""
                    ]
                  ]
                }
              }
            },
            "Index": 5.0
          }
        ],
        "Information": {
          "State": "Warning",
          "Message": "Length: 0.06",
          "Tooltip": "Threshold:\n\t\\\\?\\Volume{c74cfac6-76fc-49d4-9acd-13e45799a56a}\\: Free space = 135.06 MB",
          "TimeSpan": "00:00:07.1600000",
          "Date": "2016-11-10T14:07:59.4991129+01:00",
          "Boolean": true
        },
        "TestScanResults": [
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "1",
              "Tooltip": "",
              "TimeSpan": "00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 0.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "",
              "Tooltip": "2",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 1.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Warning",
              "Message": "",
              "Tooltip": "Threshold:\n\t\\\\?\\Volume{c74cfac6-76fc-49d4-9acd-13e45799a56a}\\: Free space = 135.06 MB",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 3.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "SD: 6.32%",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 4.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "URT: 4315 MB",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 5.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "RD: 0%",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 6.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "Length: 0.06",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 7.0
          }
        ],
        "Index": 0.0
      },
      {
        "ScanComponentResults": [
          {
            "$testType": "Test",
            "Results": [
              {
                "Name": "RAT",
                "IsUp": true
              },
              {
                "Name": "LUT",
                "IsUp": true
              }
            ],
            "Information": {
              "State": "Up",
              "Message": "Step 1",
              "Tooltip": "",
              "TimeSpan": "00:00:00.2710000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "Index": 0.0
          },
          {
            "$testType": "Test",
            "Information": {
              "State": "Warning",
              "Message": "STRT Succeeded",
              "Tooltip": "9",
              "TimeSpan": "00:00:00",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "Results": {
              "0": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "1": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "2": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "3": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "4": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "5": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "6": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "7": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              },
              "8": {
                "State": "Down",
                "Message": "State3",
                "Value": null,
                "Time": "-00:00:00.0010000"
              }
            },
            "Index": 1.0
          }
        ],
        "Information": {
          "State": "Down",
          "Message": "Total",
          "Tooltip": "Total1",
          "TimeSpan": "00:00:00",
          "Date": "2016-11-10T14:07:59.4991129+01:00",
          "Boolean": true
        },
        "TestScanResults": [
          {
           "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "Step4",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 0.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "",
              "Tooltip": "Step4",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 1.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "",
              "Tooltip": "Total",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 2.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "Last",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 3.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Up",
              "Message": "Previous",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 4.0
          },
          {
            "ScanComponentResults": [],
           "Information": {
              "State": "Down",
              "Message": "Not",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 5.0
          },
          {
            "ScanComponentResults": [],
            "Information": {
              "State": "Down",
              "Message": "Not",
              "Tooltip": "",
              "TimeSpan": "-00:00:00.0010000",
              "Date": "2016-11-10T14:07:59.4991129+01:00",
              "Boolean": true
            },
            "TestScanResults": [],
            "Index": 6.0
          }
        ],
        "Index": 1.0
      }
    ],
    "Information": {
      "State": "Warning",
      "Message": "Length: 0.06",
      "Tooltip": "Threshold = 500.00 MB\nDrive(s) in threshold:\n\t\\\\?\\Volume{c74cfac6-76fc-49d4-9acd-13e45799a56a}\\: Free space = 135.06 MB",
      "TimeSpan": "00:00:07.1600000",
      "Date": "2016-11-10T14:07:59+01:00",
      "Boolean": true
    },
    "AccumulatorResults": {
      "Values": {
        "accFullScan": {
          "$commonType": "Object",
          "$values": [
            null,
            null
          ]
        },
        "accBufferCacheHitRatio": {
          "$commonType": "Object",
          "$values": [
            null,
            null
          ]
        }
      }
    },
    "FirstDownDate": "1997-01-01T00:00:00+01:00",
    "ErrorCode": 0.0,
    "CalculatedUpCount": -1.0,
    "CalculatedDownCount": -1.0
  }
}



Thank you once again.

Have a good day.

**Comment by richie5um** [comment]
Hi, sorry for the delay.

I think the issue you've encountered is due to the following text in your JSON: "\\\\let\\"

This caused a problem due to the way it was trying to find an ending quote - but, one that wasn't preceded by a backslash (i.e., an escaped quote).

I've updated (and published) the extension to try to handle this scenario by trying to better discriminate escaped quotes.

Please can you update the VS extension and let me know if the problem is still there.

Thanks.

**Comment by richie5um** [comment]
Performed some more testing. It seems to work fine. Let me know if not and I'll re-open this issue. Thanks.

**Comment by dkriefgsx** [comment]
Thanks for your reply, the latest version has fixed the issue !

Great job !
