### ISSUE TITLE
Path not shown when bigger than status bar

### ISSUE THREAD

**Issue by DustinWoods** [richie5um/vscode-statusbar-json-path#9]
I've notice when the JSON path is a string too long for the status bar, the path isn't show at all.

In my use for this extension, I don't necessarily need to see the entire path, but I still need to copy the string. Is it a possible fix to show a truncated version in the status bar and have the ability to copy the full path?

**Comment by richie5um** [comment]
Hi. You should be able to use the command palette (Cmd+Shift+P => Copy current JSONPath to Clipboard).

**Comment by DustinWoods** [comment]
This is perfect, thanks!
